name: buildx

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 21 * * 5"
  push:
    branches:
      - 'master'

env:
  IMAGE_NAME: ghcr.io/truestory1/flexget
  PLATFORMS: linux/amd64 #,linux/arm64

jobs:
  buildx:
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile requirements.txt
        run: |
          docker run --rm -i -v ${PWD}:/req alpine:3.20 \
            sh -c "apk add py3-pip build-base python3-dev libffi-dev && rm /usr/lib/python*/EXTERNALLY-MANAGED && pip install pip-tools && cd /req && pip-compile -U"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Initial Buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:testing
          platforms: linux/amd64,linux/arm64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Load Built Image and Get Variables
        id: vars
        run: |
          docker buildx build \
            -t ${{ env.IMAGE_NAME }}:testing \
            --cache-to type=gha,mode=max \
            --cache-from type=gha \
            --platform=linux/amd64 \
            --load \
            .
          CID=$(docker run -d ${{ env.IMAGE_NAME }}:testing)
          VER_FULL=$(docker exec $CID flexget -V | sed -n 1p)
          echo "VER_FULL=$VER_FULL" >> $GITHUB_ENV
          docker rm -f $CID

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildx and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VER_FULL }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Commit requirements.txt
        uses: EndBug/add-and-commit@v9
        with:
          message: |
            Update requirements.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: requirements.txt
          path: requirements.txt
